language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

mysql:
  database: travis_ci_drupal_module_inspectlet_test
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*

before_script:
  - cd ../..
  - mysql -e 'create database travis_ci_drupal_module_inspectlet_test'
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/travis_ci_drupal_module_inspectlet_test --enable=simpletest inspectlet
  - ln -s $(readlink -e $(cd -)) travis_ci_drupal_module_inspectlet_test/drupal/sites/all/modules/travis_ci_drupal_module_inspectlet
  - cd travis_ci_drupal_module_inspectlet_test/drupal
  - drush --yes pm-enable travis_ci_drupal_inspectlet_example
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run 'Travis-CI Drupal inspectlet Example' --uri=http://127.0.0.1:8080

