<?php

/**
 * @file
 * Implements the necessary hook implementations.
 */

/**
 * Implements hook_help().
 */
function inspectlet_help($path, $arg) {
  switch ($path) {
    case 'admin/help/inspectlet':
      return t(
        '<a href="@inspect_url">Inspeclet</a> is a free (registration required) website user-interaction suite for your site.', 
        array(
          '@inspect_url' => 'http://www.inspectlet.com/'
        )
      );
  }
}

/**
 * Implements hook_page_alter() to insert Javascript into the page.
 */
function inspectlet_page_alter(&$page) {
  $id = variable_get('inspectlet_code');
  
  $script = 'window.__insp = window.__insp || [];' . "\n"
    . "__insp.push(['wid', ${id}]);\n"
    . "(function() {\n"
    . "  function __ldinsp(){\n"
    . "var insp = document.createElement('script');\n"
    . "insp.type = 'text/javascript';\n"
    . "insp.async = true;\n"
    . "insp.id = \"inspsync\";\n"
    . "insp.src = ('https:' == document.location.protocol ? 'https' : 'http') "
    . "+ '://cdn.inspectlet.com/inspectlet.js';\n"
    . "var x = document.getElementsByTagName('script')[0];\n"
    . "x.parentNode.insertBefore(insp, x);\n}\n"
    . "if (window.attachEvent){\n"
    . "window.attachEvent('onload', __ldinsp);\n"
    . "}else{\n"
    . "window.addEventListener('load', __ldinsp, false);\n"
    . "}})();\n";

  drupal_add_js(
    $script,
    array(
      'scope' => 'footer',
      'type' => 'inline',
    )
  );
}

/**
 * Implements hook_menu().
 */
function inspectlet_menu() {
  $items = array();
  
  $items['admin/config/system/inspectlet'] = array(
    'title' => 'Inspectlet',
    'description' => t('Enter your tracking id here.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('inspectlet_settings_form'),
    'access arguments' => array('administer inspectlet'),
    'file' => 'inspectlet.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
 function inspectlet_permission() {
   return array(
     'administer inspectlet' => array(
       'title' => t('Administer inspectlet.'),
       'description' => t('Perform maintenance tasks for inspectlet.'),
     ),
   );
 }