<?php

/**
 * @file
 * Implements the necessary hook implementations.
 */

/**
 * Implements hook_help().
 */
function inspectlet_help($path, $arg) {
  switch ($path) {
    case 'admin/help/inspectlet':
      return t(
        '<a href="@inspect_url">Inspeclet</a> is a free (registration required) website user-interaction suite for your site.', 
        array(
          '@inspect_url' => 'http://www.inspectlet.com/'
        )
      );
  }
}

/**
 * Implements hook_page_alter() to insert Javascript into the page.
 */
function inspectlet_page_alter(&$page) {
  $code = variable_get('inspectlet_code');
  
  drupal_add_js(
    $code,
    array(
      'scope' => 'footer',
      'type' => 'inline',
    )
  );
}

/**
 * Implements hook_menu().
 */
function inspectlet_menu() {
  $items = array();
  
  $items['admin/config/system/inspectlet'] = array(
    'title' => 'Inspectlet',
    'description' => t('Enter your tracking id here.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('inspectlet_settings_form'),
    'access arguments' => array('administer inspectlet'),
    'file' => 'inspectlet.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
 function inspectlet_permission() {
   return array(
     'administer inspectlet' => array(
       'title' => t('Administer inspectlet.'),
       'description' => t('Perform maintenance tasks for inspectlet.'),
     ),
   );
 }