<?php

/**
 * @file
 * Implements the necessary hook implementations.
 */

/**
 * Implements hook_help().
 */
function inspectlet_help($path, $arg) {
  switch ($path) {
    case 'admin/help/inspectlet':
      return '<a href="http://www.inspectlet.com/">Inspeclet</a> is a free (registration required) website user-interaction suite for your site.';
  }
}

/**
 * Implements hook_page_alter().
 */
function inspectlet_page_build(&$page) {
  $code = variable_get('inspectlet_js');

  $page['footer']['#attached']['js'][] = array(
    'data' => $code,
    'type' => 'inline',
  );
}

/**
 * Implements hook_menu().
 */
function inspectlet_menu() {
  $items = array();

  $items['admin/config/system/inspectlet'] = array(
    'title' => 'Inspectlet',
    'description' => 'Enter your tracking id here.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('inspectlet_settings_form'),
    'access arguments' => array('administer inspectlet'),
    'file' => 'inspectlet.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function inspectlet_permission() {
  return array(
    'administer inspectlet' => array(
      'title' => t('Administer inspectlet.'),
      'description' => t('Perform maintenance tasks for inspectlet.'),
      'restrict access' => TRUE,
    ),
  );
}
